baseURL: "/"
languageCode: en-us
title: "Cancer Genetics"
theme: ath-tufte-hugo
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _cache$
  - \.csl$
  - \.md$
  - \.utf8$
  - \.knit$
permalinks:
  post: "/:year/:month/:day/:slug/"
menu:
  main:
    - name: Overview
      url: /overview/
      weight: 1
    - name: Assignment/Project 
      url: /assignments/
      weight: 3
    - name: Syllabus
      url: /syllabus/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 4


# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Mike Hallett
  thumbnail: /images/sys-small1.png
  instructor: 
    name: Mike Hallett
    email: michael.hallett@uwo.ca
    url: "https://mikehallett.science"
    twitter: hallettmichael
    github: hallettmiket
    bitbucket: hallettlab
    office: "MSB 360"
    officehours: "Office Hours Tuesdays 4pm"
  course:
    number: "4450A"
    dates: "Fall 2023"
    days: "Tuesdays"
    time: "5:30pm-7:30pm"
    location: "MSB-M384"
    twitter: hallettmichael
    slack: "https://cancer-uwo.slack.com"
    github: "hallettmiket/hallettmiket.github.io"
    copyrightYear: "2023"
    contactDetails: Slack
  labs:
    TA: Blane Gebreyes and TBA
    email: bgebreye@uwo.ca and TBA
    location:  "TBA"
    officehours: "Office Hourse: TBA" 
  university: 
    name: Western University
    url: "https://www.uwo.ca/"
  school:
    name: "Department of Biochemistry"
    url: "https://www.schulich.uwo.ca/biochem/"
  description: "Molecular Genetics of Human Cancer"
  primaryColor: "#1663BA"
  secondaryColor: "#398AE6"
  credits: "We thank [A Heiss](https://www.andrewheiss.com/) for the modified Tufte scheme. "
  
  logo: 
    url: /images/western_schulich_compbio.png
    alt: Genetic basis of cancer
  meta:
    twitterSite: "@hallettmichael"
    twitterCreator: "@hallettmichael"

markup:
  goldmark:
    renderer:
      unsafe: true

