baseURL: "/"
languageCode: en-us
title: "Cancer Genetics"
theme: ath-tufte-hugo
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.yaml$
  - _cache$
  - \.csl$
  - \.md$
  - \.utf8$
  - \.knit$
permalinks:
  post: "/:year/:month/:day/:slug/"
menu:
  main:
    - name: Overview
      url: /overview/
      weight: 1
    - name: Assignments 
      url: /assignments/
      weight: 4
    - name: Syllabus
      url: /syllabus/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 3
    - name: Projects
      url: /projects/
      weight: 5
# Disable taxonomies
taxonomies:
  tag: ""
  group: ""
  category: ""
params:
  author: Mike Hallett
  thumbnail: /images/sys-small1.png
  instructor: 
    name: Mike Hallett
    email: michael.hallett@uwo.ca
    url: "https://mikehallett.science"
    twitter: hallettmichael
    github: hallettmiket
    bitbucket: hallettlab
    office: "MSB 352"
    officehours: "Office Hours TBA"
  course:
    number: "4450A"
    dates: "Fall 2022"
    days: "Tuesdays"
    time: "5:30pm-7:30pm"
    location: "MSB-M282"
    twitter: hallettmichael
    slack: "https://cancer-genetics-uwo.slack.com"
    youtube: "https://www.youtube.com/channel/UCx3QJc2DZSo-mny8UERmywg?view_as=subscriber"
    github: "hallettmiket/hallettmiket.github.io"
    copyrightYear: "2022"
    contactDetails: Slack
  labs:
    TA: TBA
    email: TBA
    location:  "TBA"
    labtime: "TBA"
    officehours: "Office Hourse: TBA" 
  university: 
    name: Western University
    url: "https://www.uwo.ca/"
  school:
    name: "Department of Biochemistry"
    url: "https://www.schulich.uwo.ca/biochem/"
  description: "Molecular Genetics of Human Cancer"
  primaryColor: "#1663BA"
  secondaryColor: "#398AE6"
  credits: "We thank [A Heiss](https://www.andrewheiss.com/) for the modified Tufte scheme. "
  
  logo: 
    url: /images/western_schulich_compbio.png
    alt: Genetic basis of cancer
  meta:
    twitterSite: "@hallettmichael"
    twitterCreator: "@hallettmichael"

markup:
  goldmark:
    renderer:
      unsafe: true

