---
title: "Orientation and the first 6 hallmarks"
date: "2022-08-08"
---

Readings  should be completed _before_ the actual lecture. 
The lecture itself is intended to provide a deeper exposition of the material and provide additional insight.
 
# Required 
   
  
- Please read the [Overview](/overview/) for the course and familiarize yourself with the content at OWL.^[Required reading represents fundamental material that you are expected to master. You can be tested on this material.]   
 
  
- Please read the [Resources](/resources/) for the course.  
  

- [The Hallmarks of Cancer](https://www.cell.com/fulltext/S0092-8674(00)81683-9) Hanahan and Weinberg (2000) Cell. Volume 100, Issue 1.

 

- Consider the two textbooks [The biology of cancer, 2nd edition](https://blackwells.co.uk/bookshop/product/9780815345282?gC=4cfad707612&gclid=Cj0KCQjwhqaVBhCxARIsAHK1tiOHyQt9hNtV0wc4wwIVY0L6DOpitcP_vIoaLmcQteP5j8483x_bL7AaArSKEALw_wcB) from R. Weinberg and [Molecular biology of cancer, 5th edition](https://blackwells.co.uk/bookshop/product/9780198833024?gC=4cfad707612&gclid=Cj0KCQjwhqaVBhCxARIsAHK1tiPR03yNqRZ7pwJDMHSbVY6ZOg1RZR7MHYyl_OUCDg2cef3wvcYqmnEaAqSSEALw_wcB) from L. Pecorino.
 
# Recommended

Please make sure that you understand the concept of quiescence and how it differs from normal cell cycle.

- Chapter 5 of RA Weinberg, The biology of cancer.

- [Movie about DNA replication](https://www.youtube.com/watch?v=TNKWgcFPHqw)

- Coller HA (2011) The essence of quiescence. [Science](doi:10.1126/science.1216242).


# Complementary

- Witsch et al. (2010) Roles for growth factors in cancer progression. [Physiology](doi:10.1152/physiol.00045.2009) 

# Action items  

- Ensure that you are familiar with the [OWL course page](https://owl.uwo.ca/x/gGWomX).


- Using your UWO email acccount, join the Slack workspace at [cancer-genetics-uwo.slack.com](https://cancer-genetics-uwo.slack.com)

 
 
# Points of reflection

- Throughout the course exercises including assignments, exams and projects, it is expected that you have chosen a specific cancer type, a specific pathway or process, and a specific gene. The gene, pathway and process are ideally of special interest in your chosen cancer type.

For example, I might choose invasive ductal breast carcinoma with a focus on Akt-mediated signalling and the Human Epidermal Growth Factor 2 (HER2). 
